--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrHoller/FShop
build-by-default: true
branches:
- PM-4
projects:
  FShop:
    path: FShop/
    libs:
      - src: mrholler\simpleforms
        version: ~4.0.0
        branch: master
...
